# Generated by Django 4.1 on 2022-09-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmscatalog",
            name="new_film",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="filmscatalog",
            name="title_for_url",
            field=models.URLField(default="#", max_length=30),
        ),
    ]
